---
member:
  testuser:
    password: P@ssw0rd
    todo_list:
    - name: First To Do
      deadline: '2025-05-09T12:00:00'
      urgency: High
    - name: Homework
      deadline: '2025-05-10T09:00:00'
      urgency: Medium
    - name: Meeting
      deadline: '2025-05-11T12:00:00'
      urgency: Medium
    - name: Football Game
      deadline: '2025-05-15T16:00:00'
      urgency: High
